### ISSUE TITLE
index.d.ts should be the only d.ts file allowed in tsconfig.json

### ISSUE THREAD

**Issue by sandersn** [microsoft/types-publisher#708]
Currently, tsconfig.json for each package contains all the test files and all the type files. However, for the test files, this doesn't reflect how users will reference the type files as installed in `@types/*`. This matters when a package has a global augmentation:

```ts
// @filename: globals.d.ts
declare global {
   function glo(n: number): void
}
// @filename: index.d.ts
export const x = 1

// @filename: package-tests.ts
import { x } from 'package'
// @filename: global-tests.ts
glo(1)
```

When `@types/package` is actually installed, the last file, `global-tests.ts`, is incorrectly able to resolve `glo` without having 

```
/// <reference types="package/globals" />
```

At the top. That's because the in-DT tsconfig currently looks like this:

```json
...
"files": [
  "index.d.ts",
  "globals.d.ts",
  "package-tests.ts",
  "global-tests.ts"
]
```

Only `index.d.ts` should be allowed of the types files:

```json
...
"files": [
  "index.d.ts",
  "package-tests.ts",
  "global-tests.ts"
]
```

Everything else should be referenced either through `index.d.ts` or through an explicit reference in the tests. That's because users shouldn't have references in their `"files"` like `node_modules/@types/package/global-tests.ts`.

Fixing this will require a couple of changes:

1. dtslint will need a rule that checks tsconfig and disallows all d.ts except `index.d.ts`.
2. types-publisher will need to follow dependencies in tests too. Right now it doesn't.

d.ts files that aren't tested and aren't used need to be added to `UNUSED_FILES.txt`. Previously they could just be added to `"files"` in tsconfig. Because UNUSED_FILES.txt will not include files that *might* be used, but happen to have no tests, I'm going to rename it to OTHER_FILES.txt.

So, this bug will have five associated PRs:

- [x] Types-publisher: Rename UNUSED_FILES.txt to OTHER_FILES.txt (#709)
- [x] Rename 6 UNUSED_FILES.txt to OTHER_FILES.txt in existing DT packages. (DefinitelyTyped/DefinitelyTyped#40479)
- [x] Types-publisher: start following references in tests for calculating unused files. (#710)
- [ ] Drop already-referenced files from about 250 tsconfig.jsons. (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40676)
- [ ] Move unreferenced files from about 102 tsconfig.jsons to OTHER_FILES.txt. (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40676)
- [ ] Document in README.md (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40677)
- [x] File follow-up issue on Typescript for typeReference not respecting baseUrl/typeRoots (https://github.com/microsoft/TypeScript/issues/35365)
- [ ] Publicise change on Twitter.
- [x] Check dts-gen to see how it generates the file list.

I combined the last two steps together because I believe that the change will not break DT. I sent out a series of small fixup PRs first.

**Comment by sandersn** [comment]
@andrewbranch @RyanCavanaugh @DanielRosenwasser in case you're interested or have opinions.

**Comment by DanielRosenwasser** [comment]
> Everything else should be referenced either through index.d.ts or through an explicit reference in the tests.

Better make that a rule too!

**Comment by andrewbranch** [comment]
>  this doesn't reflect how users will reference the type files as installed in @types/*. 

> incorrectly able to resolve `glo`

Just to clarify, you’re implicitly referring to the fact that the compiler’s resolution rules use only the @types package’s `index.d.ts` as an entry point (or more accurately, it will follow the package.json `types` field, which is already enforced to be `index.d.ts` by types-publisher), correct? So the goal is to make resolution the same for tests as it is for users.

**Comment by andrewbranch** [comment]
Assuming I understood that right, this sounds like a good idea.

**Comment by sandersn** [comment]
@DanielRosenwasser types-publisher's checks are already pretty strict about ignoring files. There are a lot of quasi-ignored files that will move from tsconfig to OTHER_FILES.txt as part of this change. I think it's important to have an opt-out so that people don't have to test their types exhaustively, but it's also important that those opted-out files look different.

@andrewbranch You are right.

**Comment by ExE-Boss** [comment]
I&nbsp;actually tried&nbsp;to&nbsp;explicitly declare&nbsp;`/// <reference types="*"/>` in&nbsp;my&nbsp;UMD&nbsp;`@types`&nbsp;definitions, but&nbsp;`dtslint`&nbsp;complained that&nbsp;it’s&nbsp;unnecessary and&nbsp;caused&nbsp;build&nbsp;failures.

**Comment by sandersn** [comment]
`"*"`? That is equivalent to `import "*"` -- I don't think it resolves to anything.

**Comment by ExE-Boss** [comment]
`import "*"` makes the file be parsed as a module, thus making the **UMD** `export as namespace` inaccessible.

`/// <reference types="*">` keeps the file parsed as is, and with no `import` or `export`s, **UMD** `export as namespace` definitions are accessible.

`"*"` in this context means `"<module_name>"`.

**Comment by sandersn** [comment]
Oh, I see. I didn't get the meaning of `*` before.

Even after closing this issue, `index.d.ts` has special handling and is implicitly included, as your example shows, even when it's not correct. I'm not sure how to fix that. We'd have to make it inaccessible only to tests of globals, not of modules.

**Comment by ExE-Boss** [comment]
Actually, it’s&nbsp;`types‑publisher` that&nbsp;doesn’t like&nbsp;`<reference />` to&nbsp;self in&nbsp;**UMD**&nbsp;tests, which&nbsp;is&nbsp;why I&nbsp;couldn’t&nbsp;reproduce this&nbsp;locally (since&nbsp;`types‑publisher` doesn’t&nbsp;like my&nbsp;environment for&nbsp;whatever&nbsp;reason, and&nbsp;therefore I&nbsp;run&nbsp;`dtslint`&nbsp;directly).
